// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  d2Sidebar: [{type: 'autogenerated', dirName: 'd2docs'}],
  richbotSidebar :[{type: 'autogenerated', dirName: 'richbot'}],

  mainSidebar: [
    'welcome',
  ],

};

module.exports = sidebars;
